// Map names utility for converting map IDs to human-readable names
export interface MapNamesData {
  map_names: Record<string, string>;
  metadata: {
    source: string;
    total_maps: number;
    first_indoor_map: number;
    num_city_maps: number;
    description: string;
  };
}

const mapNames: MapNamesData = {
  map_names: {
    '0x00': 'PALLET TOWN',
    '0x01': 'VIRIDIAN CITY',
    '0x02': 'PEWTER CITY',
    '0x03': 'CERULEAN CITY',
    '0x04': 'LAVENDER TOWN',
    '0x05': 'VERMILION CITY',
    '0x06': 'CELADON CITY',
    '0x07': 'FUCHSIA CITY',
    '0x08': 'CINNABAR ISLAND',
    '0x09': 'INDIGO PLATEAU',
    '0x0A': 'SAFFRON CITY',
    '0x0B': 'UNUSED_MAP_0B',
    '0x0C': 'ROUTE 1',
    '0x0D': 'ROUTE 2',
    '0x0E': 'ROUTE 3',
    '0x0F': 'ROUTE 4',
    '0x10': 'ROUTE 5',
    '0x11': 'ROUTE 6',
    '0x12': 'ROUTE 7',
    '0x13': 'ROUTE 8',
    '0x14': 'ROUTE 9',
    '0x15': 'ROUTE 10',
    '0x16': 'ROUTE 11',
    '0x17': 'ROUTE 12',
    '0x18': 'ROUTE 13',
    '0x19': 'ROUTE 14',
    '0x1A': 'ROUTE 15',
    '0x1B': 'ROUTE 16',
    '0x1C': 'ROUTE 17',
    '0x1D': 'ROUTE 18',
    '0x1E': 'SEA ROUTE 19',
    '0x1F': 'SEA ROUTE 20',
    '0x20': 'SEA ROUTE 21',
    '0x21': 'ROUTE 22',
    '0x22': 'ROUTE 23',
    '0x23': 'ROUTE 24',
    '0x24': 'ROUTE 25',
    '0x25': 'PALLET TOWN',
    '0x26': 'PALLET TOWN',
    '0x27': 'PALLET TOWN',
    '0x28': 'PALLET TOWN',
    '0x29': 'VIRIDIAN CITY',
    '0x2A': 'VIRIDIAN CITY',
    '0x2B': 'VIRIDIAN CITY',
    '0x2C': 'VIRIDIAN CITY',
    '0x2D': 'VIRIDIAN CITY',
    '0x2E': "DIGLETT'S CAVE",
    '0x2F': 'VIRIDIAN FOREST',
    '0x30': 'ROUTE 2',
    '0x31': 'ROUTE 2',
    '0x32': 'VIRIDIAN FOREST',
    '0x33': 'VIRIDIAN FOREST',
    '0x34': 'PEWTER CITY',
    '0x35': 'PEWTER CITY',
    '0x36': 'PEWTER CITY',
    '0x37': 'PEWTER CITY',
    '0x38': 'PEWTER CITY',
    '0x39': 'PEWTER CITY',
    '0x3A': 'PEWTER CITY',
    '0x3B': 'MT.MOON',
    '0x3C': 'MT.MOON',
    '0x3D': 'MT.MOON',
    '0x3E': 'CERULEAN CITY',
    '0x3F': 'CERULEAN CITY',
    '0x40': 'CERULEAN CITY',
    '0x41': 'CERULEAN CITY',
    '0x42': 'CERULEAN CITY',
    '0x43': 'CERULEAN CITY',
    '0x44': 'MT.MOON',
    '0x45': 'CERULEAN CITY',
    '0x46': 'ROUTE 5',
    '0x47': 'UNDERGROUND PATH',
    '0x48': 'ROUTE 5',
    '0x49': 'ROUTE 6',
    '0x4A': 'UNDERGROUND PATH',
    '0x4B': 'UNDERGROUND PATH',
    '0x4C': 'ROUTE 7',
    '0x4D': 'UNDERGROUND PATH',
    '0x4E': 'UNDERGROUND PATH',
    '0x4F': 'ROUTE 8',
    '0x50': 'UNDERGROUND PATH',
    '0x51': 'ROCK TUNNEL',
    '0x52': 'ROCK TUNNEL',
    '0x53': 'POWER PLANT',
    '0x54': 'ROUTE 11',
    '0x55': "DIGLETT'S CAVE",
    '0x56': 'ROUTE 11',
    '0x57': 'ROUTE 12',
    '0x58': 'SEA COTTAGE',
    '0x59': 'VERMILION CITY',
    '0x5A': 'VERMILION CITY',
    '0x5B': 'VERMILION CITY',
    '0x5C': 'VERMILION CITY',
    '0x5D': 'VERMILION CITY',
    '0x5E': 'VERMILION CITY',
    '0x5F': 'S.S.ANNE',
    '0x60': 'S.S.ANNE',
    '0x61': 'S.S.ANNE',
    '0x62': 'S.S.ANNE',
    '0x63': 'S.S.ANNE',
    '0x64': 'S.S.ANNE',
    '0x65': 'S.S.ANNE',
    '0x66': 'S.S.ANNE',
    '0x67': 'S.S.ANNE',
    '0x68': 'S.S.ANNE',
    '0x69': 'UNUSED_MAP_69',
    '0x6A': 'UNUSED_MAP_6A',
    '0x6B': 'UNUSED_MAP_6B',
    '0x6C': 'VICTORY ROAD',
    '0x6D': 'UNUSED_MAP_6D',
    '0x6E': 'UNUSED_MAP_6E',
    '0x6F': 'UNUSED_MAP_6F',
    '0x70': 'UNUSED_MAP_70',
    '0x71': '#MON LEAGUE',
    '0x72': 'UNUSED_MAP_72',
    '0x73': 'UNUSED_MAP_73',
    '0x74': 'UNUSED_MAP_74',
    '0x75': 'UNUSED_MAP_75',
    '0x76': '#MON LEAGUE',
    '0x77': 'UNDERGROUND PATH',
    '0x78': '#MON LEAGUE',
    '0x79': 'UNDERGROUND PATH',
    '0x7A': 'CELADON CITY',
    '0x7B': 'CELADON CITY',
    '0x7C': 'CELADON CITY',
    '0x7D': 'CELADON CITY',
    '0x7E': 'CELADON CITY',
    '0x7F': 'CELADON CITY',
    '0x80': 'CELADON CITY',
    '0x81': 'CELADON CITY',
    '0x82': 'CELADON CITY',
    '0x83': 'CELADON CITY',
    '0x84': 'CELADON CITY',
    '0x85': 'CELADON CITY',
    '0x86': 'CELADON CITY',
    '0x87': 'CELADON CITY',
    '0x88': 'CELADON CITY',
    '0x89': 'CELADON CITY',
    '0x8A': 'CELADON CITY',
    '0x8B': 'CELADON CITY',
    '0x8C': 'CELADON CITY',
    '0x8D': 'LAVENDER TOWN',
    '0x8E': '#MON TOWER',
    '0x8F': '#MON TOWER',
    '0x90': '#MON TOWER',
    '0x91': '#MON TOWER',
    '0x92': '#MON TOWER',
    '0x93': '#MON TOWER',
    '0x94': '#MON TOWER',
    '0x95': 'LAVENDER TOWN',
    '0x96': 'LAVENDER TOWN',
    '0x97': 'LAVENDER TOWN',
    '0x98': 'FUCHSIA CITY',
    '0x99': 'FUCHSIA CITY',
    '0x9A': 'FUCHSIA CITY',
    '0x9B': 'FUCHSIA CITY',
    '0x9C': 'SAFARI ZONE',
    '0x9D': 'FUCHSIA CITY',
    '0x9E': 'FUCHSIA CITY',
    '0x9F': 'SEAFOAM ISLANDS',
    '0xA0': 'SEAFOAM ISLANDS',
    '0xA1': 'SEAFOAM ISLANDS',
    '0xA2': 'SEAFOAM ISLANDS',
    '0xA3': 'VERMILION CITY',
    '0xA4': 'FUCHSIA CITY',
    '0xA5': '<PKMN> MANSION',
    '0xA6': 'CINNABAR ISLAND',
    '0xA7': 'CINNABAR ISLAND',
    '0xA8': 'CINNABAR ISLAND',
    '0xA9': 'CINNABAR ISLAND',
    '0xAA': 'CINNABAR ISLAND',
    '0xAB': 'CINNABAR ISLAND',
    '0xAC': 'CINNABAR ISLAND',
    '0xAD': 'CINNABAR ISLAND',
    '0xAE': 'INDIGO PLATEAU',
    '0xAF': 'SAFFRON CITY',
    '0xB0': 'SAFFRON CITY',
    '0xB1': 'SAFFRON CITY',
    '0xB2': 'SAFFRON CITY',
    '0xB3': 'SAFFRON CITY',
    '0xB4': 'SAFFRON CITY',
    '0xB5': 'SILPH CO.',
    '0xB6': 'SAFFRON CITY',
    '0xB7': 'SAFFRON CITY',
    '0xB8': 'ROUTE 15',
    '0xB9': 'ROUTE 15',
    '0xBA': 'ROUTE 16',
    '0xBB': 'ROUTE 16',
    '0xBC': 'ROUTE 16',
    '0xBD': 'ROUTE 12',
    '0xBE': 'ROUTE 18',
    '0xBF': 'ROUTE 18',
    '0xC0': 'SEAFOAM ISLANDS',
    '0xC1': 'ROUTE 22',
    '0xC2': 'VICTORY ROAD',
    '0xC3': 'ROUTE 12',
    '0xC4': 'VERMILION CITY',
    '0xC5': "DIGLETT'S CAVE",
    '0xC6': 'VICTORY ROAD',
    '0xC7': 'ROCKET HQ',
    '0xC8': 'ROCKET HQ',
    '0xC9': 'ROCKET HQ',
    '0xCA': 'ROCKET HQ',
    '0xCB': 'ROCKET HQ',
    '0xCC': 'UNUSED_MAP_CC',
    '0xCD': 'UNUSED_MAP_CD',
    '0xCE': 'UNUSED_MAP_CE',
    '0xCF': 'SILPH CO.',
    '0xD0': 'SILPH CO.',
    '0xD1': 'SILPH CO.',
    '0xD2': 'SILPH CO.',
    '0xD3': 'SILPH CO.',
    '0xD4': 'SILPH CO.',
    '0xD5': 'SILPH CO.',
    '0xD6': '<PKMN> MANSION',
    '0xD7': '<PKMN> MANSION',
    '0xD8': '<PKMN> MANSION',
    '0xD9': 'SAFARI ZONE',
    '0xDA': 'SAFARI ZONE',
    '0xDB': 'SAFARI ZONE',
    '0xDC': 'SAFARI ZONE',
    '0xDD': 'SAFARI ZONE',
    '0xDE': 'SAFARI ZONE',
    '0xDF': 'SAFARI ZONE',
    '0xE0': 'SAFARI ZONE',
    '0xE1': 'SAFARI ZONE',
    '0xE2': 'CERULEAN CAVE',
    '0xE3': 'CERULEAN CAVE',
    '0xE4': 'CERULEAN CAVE',
    '0xE5': 'LAVENDER TOWN',
    '0xE6': 'CERULEAN CITY',
    '0xE7': 'UNUSED_MAP_E7',
    '0xE8': 'ROCK TUNNEL',
    '0xE9': 'SILPH CO.',
    '0xEA': 'SILPH CO.',
    '0xEB': 'SILPH CO.',
    '0xEC': 'SILPH CO.',
    '0xED': 'UNUSED_MAP_ED',
    '0xEE': 'UNUSED_MAP_EE',
    '0xEF': 'TRADE CENTER',
    '0xF0': 'COLOSSEUM',
    '0xF1': 'UNUSED_MAP_F1',
    '0xF2': 'UNUSED_MAP_F2',
    '0xF3': 'UNUSED_MAP_F3',
    '0xF4': 'UNUSED_MAP_F4',
    '0xF5': '#MON LEAGUE',
    '0xF6': '#MON LEAGUE',
    '0xF7': '#MON LEAGUE',
  },
  metadata: {
    source: 'Pokemon Red ROM disassembly',
    total_maps: 248,
    first_indoor_map: 37,
    num_city_maps: 11,
    description:
      'Map ID to display name mapping for Pokemon Red. Indoor maps (ID >= 0x25) are mapped to their parent location names based on the town map system.',
  },
};

export function getMapName(mapId: number | undefined | null): string {
  if (mapId === undefined || mapId === null) {
    return 'Unknown';
  }

  const hexId = `0x${mapId.toString(16).toUpperCase().padStart(2, '0')}`;
  return mapNames.map_names[hexId] || `Map ${mapId}`;
}

export function formatMapDisplay(mapId: number | undefined | null): string {
  if (mapId === undefined || mapId === null) {
    return 'Unknown';
  }

  const name = getMapName(mapId);
  return `${name} (${mapId})`;
}

export { mapNames };
